version: '3.8'
services:
  mysqldb:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    volumes:
      - "./scripts/baedal-sql.sql:/docker-entrypoint-initdb.d/init.sql"        
    healthcheck:
      test: timeout 5 bash -c 'cat < /dev/null > /dev/tcp/localhost/33060'
      interval: 5s
      timeout: 5s
      retries: 12  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.2.3
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"    
      - "ES_JAVA_OPTS=-Xms750m -Xmx750m"
    ports:
      - 9200:9200
      - 9300:9300    
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl http://localhost:9200 | grep -q 'You Know, for Search'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120  
  kibana:
    image: "docker.elastic.co/kibana/kibana:8.2.3"
    environment:
      SERVERNAME: kibana
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
      xpack.security.enabled: 'false'
    ports:
      - "5601:5601"
    depends_on:
      elasticsearch:
        condition: service_healthy       
  logstash:
    image: "docker.elastic.co/logstash/logstash:8.2.3"
    volumes:
      - ./elksettings/:/etc/logstash
      - '/var/log/baedal:/var/log/baedal/'
    command: logstash -f /etc/logstash/logstash.conf        
    depends_on:
      elasticsearch:
        condition: service_healthy   
  user-mgmt-service:
    image: techsriman/usermgmtservice:1.0
    environment:  
      SPRING_DATASOURCE_URL: 'jdbc:mysql://mysqldb:3306/baedalusermgmtdb'
      SPRING_DATASOURCE_USERNAME: 'root'
      SPRING_DATASOURCE_PASSWORD: 'root'
      SPRING_DATASOURCE_HIKARI_MAXIMUM-POOL-SIZE: 10            
      USERMGMTSERVICE_TEMPLATES_DIR: '/templates'      
      LOGGING_LOGBACK_ROLLINGPOLICY_MAX-FILE-SIZE: 500MB
    depends_on:
      elasticsearch:
        condition: service_healthy
      mysqldb:
        condition: service_healthy              
    ports:
      - 9090:9090
    volumes:
      - './templates:/templates'
      - '/var/log/baedal:/var/log/baedal/'
  pickup-delivery-mgmt-service:
    image: techsriman/pickupdeliverymgmtservice:1.0
    environment:  
      SPRING_DATASOURCE_URL: 'jdbc:mysql://mysqldb:3306/baedalpickupanddeliverymgmtdb'
      SPRING_DATASOURCE_USERNAME: 'root'
      SPRING_DATASOURCE_PASSWORD: 'root'
      SPRING_DATASOURCE_HIKARI_MAXIMUM-POOL-SIZE: 10            
      PICKUPANDDELIVERYSERVICE_TEMPLATES_DIR: '/templates'      
      LOGGING_LOGBACK_ROLLINGPOLICY_MAX-FILE-SIZE: 500MB
    depends_on:
      elasticsearch:
        condition: service_healthy
      mysqldb:
        condition: service_healthy      
    ports:
      - 9092:9092
    volumes:
      - './templates:/templates'  
      - '/var/log/baedal:/var/log/baedal/'
  partner-store-service:
    image: techsriman/partnerstoreservice:1.0
    environment:  
      SPRING_DATASOURCE_URL: 'jdbc:mysql://mysqldb:3306/baedalpartnerstoredb'
      SPRING_DATASOURCE_USERNAME: 'root'
      SPRING_DATASOURCE_PASSWORD: 'root'
      SPRING_DATASOURCE_HIKARI_MAXIMUM-POOL-SIZE: 10            
      PARTNERSTORESERVICE_TEMPLATES_DIR: '/templates'        
      LOGGING_LOGBACK_ROLLINGPOLICY_MAX-FILE-SIZE: 500MB
    depends_on:
      elasticsearch:
        condition: service_healthy
      mysqldb:
        condition: service_healthy      
    ports:
      - 9091:9091
    volumes:
      - './templates:/templates'  
      - '/var/log/baedal:/var/log/baedal/'
  baedalcustomer:
    image: techsriman/baedalcustomer:1.0
    environment:        
      USERACCOUNTSERVICE_URL: 'http://user-mgmt-service:9090'     
      PARTNERSTORESERVICE_URL: 'http://partner-store-service:9091'
      PICKUPANDDELIVERYSERVICE_URL: 'http://pickup-delivery-mgmt-service:9092'
      USERMGMTSERVICE_TEMPLATES_DIR: '/templates'
      BAEDAL_DEFAULT_URL: 'http://localhost:8082'
      LOGGING_LOGBACK_ROLLINGPOLICY_MAX-FILE-SIZE: 500MB
    depends_on:
      elasticsearch:
        condition: service_healthy
      mysqldb:
        condition: service_healthy     
      user-mgmt-service:
        condition: service_started
      partner-store-service:
        condition: service_started
      pickup-delivery-mgmt-service:
        condition: service_started  
    ports:
      - 8082:8082       
    volumes:    
      - '/var/log/baedal:/var/log/baedal/'
  

